-- Requires migrations 001 and 002. Additive and re-runnable; no grants or source data edits.
CREATE TABLE IF NOT EXISTS emcore_business_card_countries (
 code CHAR(2) PRIMARY KEY, name_fa VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL,
 sort_order INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emcore_business_cards (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 contact_name VARCHAR(500) DEFAULT NULL, organization_name VARCHAR(500) DEFAULT NULL,
 contact_key VARCHAR(500) DEFAULT NULL, organization_key VARCHAR(500) DEFAULT NULL,
 job_title VARCHAR(500) DEFAULT NULL, business_country_code CHAR(2) DEFAULT NULL,
 source_category VARCHAR(255) DEFAULT NULL, related_unit VARCHAR(255) DEFAULT NULL,
 activity TEXT DEFAULT NULL, notes MEDIUMTEXT DEFAULT NULL,
 review_status ENUM('needs_review','reviewed') NOT NULL DEFAULT 'needs_review',
 record_origin ENUM('imported','manual') NOT NULL,
 create_request_id CHAR(32) DEFAULT NULL, create_payload_hash CHAR(64) DEFAULT NULL,
 created_by_usr_uid CHAR(32) NOT NULL, updated_by_usr_uid CHAR(32) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at DATETIME DEFAULT NULL, lock_version INT UNSIGNED NOT NULL DEFAULT 1,
 UNIQUE KEY uq_bc_create (created_by_usr_uid,create_request_id),
 KEY ix_bc_country (business_country_code,deleted_at,id), KEY ix_bc_unit (related_unit,deleted_at),
 KEY ix_bc_names (contact_key(100),organization_key(100)),
 FOREIGN KEY (business_country_code) REFERENCES emcore_business_card_countries(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emcore_business_card_contact_points (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, card_id BIGINT UNSIGNED NOT NULL,
 kind ENUM('phone','mobile','fax','email','website','messenger','other') NOT NULL,
 label VARCHAR(255) DEFAULT NULL, raw_value VARCHAR(1000) NOT NULL,
 normalized_value VARCHAR(1000) DEFAULT NULL, sort_order INT UNSIGNED NOT NULL DEFAULT 0,
 KEY ix_bc_point (card_id,sort_order), KEY ix_bc_point_match (kind,normalized_value(190)),
 FOREIGN KEY (card_id) REFERENCES emcore_business_cards(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emcore_business_card_locations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, card_id BIGINT UNSIGNED NOT NULL,
 label VARCHAR(255) DEFAULT NULL, country_code CHAR(2) DEFAULT NULL,
 region_name VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL,
 address MEDIUMTEXT DEFAULT NULL, postal_code VARCHAR(100) DEFAULT NULL,
 latitude DECIMAL(10,7) DEFAULT NULL, longitude DECIMAL(10,7) DEFAULT NULL,
 accuracy ENUM('address','street','city','unknown') NOT NULL DEFAULT 'unknown',
 source_note TEXT DEFAULT NULL, source_urls MEDIUMTEXT DEFAULT NULL,
 sort_order INT UNSIGNED NOT NULL DEFAULT 0,
 KEY ix_bc_location (card_id,sort_order), KEY ix_bc_location_country (country_code,city),
 FOREIGN KEY (card_id) REFERENCES emcore_business_cards(id),
 FOREIGN KEY (country_code) REFERENCES emcore_business_card_countries(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emcore_business_card_files (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, card_id BIGINT UNSIGNED NOT NULL,
 original_filename VARCHAR(255) NOT NULL, stored_filename VARCHAR(80) NOT NULL,
 thumbnail_filename VARCHAR(80) DEFAULT NULL, mime_type VARCHAR(50) NOT NULL,
 size_bytes BIGINT UNSIGNED NOT NULL, width INT UNSIGNED NOT NULL, height INT UNSIGNED NOT NULL,
 sha256 CHAR(64) NOT NULL, thumbnail_sha256 CHAR(64) DEFAULT NULL,
 request_id CHAR(32) NOT NULL, payload_hash CHAR(64) NOT NULL,
 uploaded_by_usr_uid CHAR(32) NOT NULL, replaces_file_id BIGINT UNSIGNED DEFAULT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 superseded_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL,
 current_card_id BIGINT UNSIGNED GENERATED ALWAYS AS
   (CASE WHEN superseded_at IS NULL AND deleted_at IS NULL THEN card_id ELSE NULL END) STORED,
 UNIQUE KEY uq_bc_one_current_image (current_card_id),
 UNIQUE KEY uq_bc_upload_request (uploaded_by_usr_uid,request_id), KEY ix_bc_image_hash (sha256),
 FOREIGN KEY (card_id) REFERENCES emcore_business_cards(id),
 FOREIGN KEY (replaces_file_id) REFERENCES emcore_business_card_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emcore_business_card_import_batches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, source_hash CHAR(64) NOT NULL,
 actor_usr_uid CHAR(32) NOT NULL, imported_count INT UNSIGNED NOT NULL DEFAULT 0,
 skipped_count INT UNSIGNED NOT NULL DEFAULT 0, changed_count INT UNSIGNED NOT NULL DEFAULT 0,
 failed_count INT UNSIGNED NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 completed_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emcore_business_card_source_records (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, card_id BIGINT UNSIGNED NOT NULL,
 batch_id BIGINT UNSIGNED NOT NULL, source_key VARCHAR(500) NOT NULL,
 legacy_source_id VARCHAR(100) DEFAULT NULL, raw_text MEDIUMTEXT NOT NULL,
 extracted_data MEDIUMTEXT NOT NULL, image_relative_path VARCHAR(1000) DEFAULT NULL,
 content_hash CHAR(64) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_bc_source (source_key), FOREIGN KEY (card_id) REFERENCES emcore_business_cards(id),
 FOREIGN KEY (batch_id) REFERENCES emcore_business_card_import_batches(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS emcore_business_card_download_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, card_id BIGINT UNSIGNED NOT NULL,
 file_id BIGINT UNSIGNED NOT NULL, actor_usr_uid CHAR(32) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (card_id) REFERENCES emcore_business_cards(id),
 FOREIGN KEY (file_id) REFERENCES emcore_business_card_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO emcore_modules (module_key,name_fa,name_en,sort_order)
VALUES ('business_cards','کارت‌های ویزیت','Business cards',150)
ON DUPLICATE KEY UPDATE name_fa=VALUES(name_fa),name_en=VALUES(name_en),is_active=1;

-- Fixed country reference seed follows; no external lookup is needed at runtime.
INSERT IGNORE INTO emcore_business_card_countries (code,name_fa,name_en) VALUES
('AD','آندورا','Andorra'),
('AE','امارات متحدهٔ عربی','United Arab Emirates'),
('AF','افغانستان','Afghanistan'),
('AG','آنتیگوا و باربودا','Antigua & Barbuda'),
('AI','آنگویلا','Anguilla'),
('AL','آلبانی','Albania'),
('AM','ارمنستان','Armenia'),
('AO','آنگولا','Angola'),
('AQ','جنوبگان','Antarctica'),
('AR','آرژانتین','Argentina'),
('AS','ساموآی امریکا','American Samoa'),
('AT','اتریش','Austria'),
('AU','استرالیا','Australia'),
('AW','آروبا','Aruba'),
('AX','جزایر آلاند','Åland Islands'),
('AZ','جمهوری آذربایجان','Azerbaijan'),
('BA','بوسنی و هرزگوین','Bosnia & Herzegovina'),
('BB','باربادوس','Barbados'),
('BD','بنگلادش','Bangladesh'),
('BE','بلژیک','Belgium'),
('BF','بورکینافاسو','Burkina Faso'),
('BG','بلغارستان','Bulgaria'),
('BH','بحرین','Bahrain'),
('BI','بوروندی','Burundi'),
('BJ','بنین','Benin'),
('BL','سن بارتلمی','St. Barthélemy'),
('BM','برمودا','Bermuda'),
('BN','برونئی','Brunei'),
('BO','بولیوی','Bolivia'),
('BQ','جزایر کارائیب هلند','Caribbean Netherlands'),
('BR','برزیل','Brazil'),
('BS','باهاما','Bahamas'),
('BT','بوتان','Bhutan'),
('BV','جزیرهٔ بووه','Bouvet Island'),
('BW','بوتسوانا','Botswana'),
('BY','بلاروس','Belarus'),
('BZ','بلیز','Belize'),
('CA','کانادا','Canada'),
('CC','جزایر کوکوس','Cocos (Keeling) Islands'),
('CD','کنگو - کینشاسا','Congo - Kinshasa'),
('CF','جمهوری افریقای مرکزی','Central African Republic'),
('CG','کنگو - برازویل','Congo - Brazzaville'),
('CH','سوئیس','Switzerland'),
('CI','ساحل عاج','Côte d’Ivoire'),
('CK','جزایر کوک','Cook Islands'),
('CL','شیلی','Chile'),
('CM','کامرون','Cameroon'),
('CN','چین','China'),
('CO','کلمبیا','Colombia'),
('CR','کاستاریکا','Costa Rica'),
('CU','کوبا','Cuba'),
('CV','کیپ‌ورد','Cape Verde'),
('CW','کوراسائو','Curaçao'),
('CX','جزیرهٔ کریسمس','Christmas Island'),
('CY','قبرس','Cyprus'),
('CZ','چک','Czechia'),
('DE','آلمان','Germany'),
('DJ','جیبوتی','Djibouti'),
('DK','دانمارک','Denmark'),
('DM','دومینیکا','Dominica'),
('DO','جمهوری دومینیکن','Dominican Republic'),
('DZ','الجزایر','Algeria'),
('EC','اکوادور','Ecuador'),
('EE','استونی','Estonia'),
('EG','مصر','Egypt'),
('EH','صحرای غربی','Western Sahara'),
('ER','اریتره','Eritrea'),
('ES','اسپانیا','Spain'),
('ET','اتیوپی','Ethiopia'),
('FI','فنلاند','Finland'),
('FJ','فیجی','Fiji'),
('FK','جزایر فالکلند','Falkland Islands'),
('FM','میکرونزی','Micronesia'),
('FO','جزایر فارو','Faroe Islands'),
('FR','فرانسه','France'),
('GA','گابن','Gabon'),
('GB','بریتانیا','United Kingdom'),
('GD','گرنادا','Grenada'),
('GE','گرجستان','Georgia'),
('GF','گویان فرانسه','French Guiana'),
('GG','گرنزی','Guernsey'),
('GH','غنا','Ghana'),
('GI','جبل‌الطارق','Gibraltar'),
('GL','گرینلند','Greenland'),
('GM','گامبیا','Gambia'),
('GN','گینه','Guinea'),
('GP','گوادلوپ','Guadeloupe'),
('GQ','گینهٔ استوایی','Equatorial Guinea'),
('GR','یونان','Greece'),
('GS','جورجیای جنوبی و جزایر ساندویچ جنوبی','South Georgia & South Sandwich Islands'),
('GT','گواتمالا','Guatemala'),
('GU','گوام','Guam'),
('GW','گینهٔ بیسائو','Guinea-Bissau'),
('GY','گویان','Guyana'),
('HK','هنگ‌کنگ، منطقهٔ ویژهٔ اداری چین','Hong Kong SAR China'),
('HM','هرد و جزایر مک‌دونالد','Heard & McDonald Islands'),
('HN','هندوراس','Honduras'),
('HR','کرواسی','Croatia'),
('HT','هائیتی','Haiti'),
('HU','مجارستان','Hungary'),
('ID','اندونزی','Indonesia'),
('IE','ایرلند','Ireland'),
('IL','اسرائیل','Israel'),
('IM','جزیرهٔ من','Isle of Man'),
('IN','هند','India'),
('IO','قلمرو بریتانیا در اقیانوس هند','British Indian Ocean Territory'),
('IQ','عراق','Iraq'),
('IR','ایران','Iran'),
('IS','ایسلند','Iceland'),
('IT','ایتالیا','Italy'),
('JE','جرزی','Jersey'),
('JM','جامائیکا','Jamaica'),
('JO','اردن','Jordan'),
('JP','ژاپن','Japan'),
('KE','کنیا','Kenya'),
('KG','قرقیزستان','Kyrgyzstan'),
('KH','کامبوج','Cambodia'),
('KI','کیریباتی','Kiribati'),
('KM','کومور','Comoros'),
('KN','سنت کیتس و نویس','St. Kitts & Nevis'),
('KP','کرهٔ شمالی','North Korea'),
('KR','کرهٔ جنوبی','South Korea'),
('KW','کویت','Kuwait'),
('KY','جزایر کِیمن','Cayman Islands'),
('KZ','قزاقستان','Kazakhstan'),
('LA','لائوس','Laos'),
('LB','لبنان','Lebanon'),
('LC','سنت لوسیا','St. Lucia'),
('LI','لیختن‌اشتاین','Liechtenstein'),
('LK','سری‌لانکا','Sri Lanka'),
('LR','لیبریا','Liberia'),
('LS','لسوتو','Lesotho'),
('LT','لیتوانی','Lithuania'),
('LU','لوکزامبورگ','Luxembourg'),
('LV','لتونی','Latvia'),
('LY','لیبی','Libya'),
('MA','مراکش','Morocco'),
('MC','موناکو','Monaco'),
('MD','مولداوی','Moldova'),
('ME','مونته‌نگرو','Montenegro'),
('MF','سنت مارتین','St. Martin'),
('MG','ماداگاسکار','Madagascar'),
('MH','جزایر مارشال','Marshall Islands'),
('MK','مقدونیهٔ شمالی','North Macedonia'),
('ML','مالی','Mali'),
('MM','میانمار (برمه)','Myanmar (Burma)'),
('MN','مغولستان','Mongolia'),
('MO','ماکائو، منطقهٔ ویژهٔ اداری چین','Macao SAR China'),
('MP','جزایر ماریانای شمالی','Northern Mariana Islands'),
('MQ','مارتینیک','Martinique'),
('MR','موریتانی','Mauritania'),
('MS','مونت‌سرات','Montserrat'),
('MT','مالت','Malta'),
('MU','موریس','Mauritius'),
('MV','مالدیو','Maldives'),
('MW','مالاوی','Malawi'),
('MX','مکزیک','Mexico'),
('MY','مالزی','Malaysia'),
('MZ','موزامبیک','Mozambique'),
('NA','نامیبیا','Namibia'),
('NC','کالدونیای جدید','New Caledonia'),
('NE','نیجر','Niger'),
('NF','جزیرهٔ نورفولک','Norfolk Island'),
('NG','نیجریه','Nigeria'),
('NI','نیکاراگوئه','Nicaragua'),
('NL','هلند','Netherlands'),
('NO','نروژ','Norway'),
('NP','نپال','Nepal'),
('NR','نائورو','Nauru'),
('NU','نیوئه','Niue'),
('NZ','نیوزیلند','New Zealand'),
('OM','عمان','Oman'),
('PA','پاناما','Panama'),
('PE','پرو','Peru'),
('PF','پلی‌نزی فرانسه','French Polynesia'),
('PG','پاپوا گینهٔ نو','Papua New Guinea'),
('PH','فیلیپین','Philippines'),
('PK','پاکستان','Pakistan'),
('PL','لهستان','Poland'),
('PM','سن پیر و میکلن','St. Pierre & Miquelon'),
('PN','جزایر پیت‌کرن','Pitcairn Islands'),
('PR','پورتوریکو','Puerto Rico'),
('PS','سرزمین‌های فلسطینی','Palestinian Territories'),
('PT','پرتغال','Portugal'),
('PW','پالائو','Palau'),
('PY','پاراگوئه','Paraguay'),
('QA','قطر','Qatar'),
('RE','رئونیون','Réunion'),
('RO','رومانی','Romania'),
('RS','صربستان','Serbia'),
('RU','روسیه','Russia'),
('RW','رواندا','Rwanda'),
('SA','عربستان سعودی','Saudi Arabia'),
('SB','جزایر سلیمان','Solomon Islands'),
('SC','سیشل','Seychelles'),
('SD','سودان','Sudan'),
('SE','سوئد','Sweden'),
('SG','سنگاپور','Singapore'),
('SH','سنت هلن','St. Helena'),
('SI','اسلوونی','Slovenia'),
('SJ','سوالبارد و یان ماین','Svalbard & Jan Mayen'),
('SK','اسلواکی','Slovakia'),
('SL','سیرالئون','Sierra Leone'),
('SM','سان‌مارینو','San Marino'),
('SN','سنگال','Senegal'),
('SO','سومالی','Somalia'),
('SR','سورینام','Suriname'),
('SS','سودان جنوبی','South Sudan'),
('ST','سائوتومه و پرینسیپ','São Tomé & Príncipe'),
('SV','السالوادور','El Salvador'),
('SX','سنت مارتن','Sint Maarten'),
('SY','سوریه','Syria'),
('SZ','اسواتینی','Eswatini'),
('TC','جزایر تورکس و کایکوس','Turks & Caicos Islands'),
('TD','چاد','Chad'),
('TF','سرزمین‌های جنوبی فرانسه','French Southern Territories'),
('TG','توگو','Togo'),
('TH','تایلند','Thailand'),
('TJ','تاجیکستان','Tajikistan'),
('TK','توکلائو','Tokelau'),
('TL','تیمور-لسته','Timor-Leste'),
('TM','ترکمنستان','Turkmenistan'),
('TN','تونس','Tunisia'),
('TO','تونگا','Tonga'),
('TR','ترکیه','Türkiye'),
('TT','ترینیداد و توباگو','Trinidad & Tobago'),
('TV','تووالو','Tuvalu'),
('TW','تایوان','Taiwan'),
('TZ','تانزانیا','Tanzania'),
('UA','اوکراین','Ukraine'),
('UG','اوگاندا','Uganda'),
('UM','جزایر دورافتادهٔ ایالات متحده','U.S. Outlying Islands'),
('US','ایالات متحده','United States'),
('UY','اروگوئه','Uruguay'),
('UZ','ازبکستان','Uzbekistan'),
('VA','واتیکان','Vatican City'),
('VC','سنت وینسنت و گرنادین','St. Vincent & Grenadines'),
('VE','ونزوئلا','Venezuela'),
('VG','جزایر ویرجین بریتانیا','British Virgin Islands'),
('VI','جزایر ویرجین ایالات متحده','U.S. Virgin Islands'),
('VN','ویتنام','Vietnam'),
('VU','وانواتو','Vanuatu'),
('WF','والیس و فوتونا','Wallis & Futuna'),
('WS','ساموآ','Samoa'),
('YE','یمن','Yemen'),
('YT','مایوت','Mayotte'),
('ZA','افریقای جنوبی','South Africa'),
('ZM','زامبیا','Zambia'),
('ZW','زیمبابوه','Zimbabwe');
