'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const panel=read('panels/emcore_meeting_minutes_panel.html'),ui=read('emcore_assets/emcore-ui.js'),moduleJs=read('emcore_assets/meeting-minutes.js');
new vm.Script(ui);new vm.Script(moduleJs);
const ids=[...panel.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'unique panel IDs');
assert.ok(!/\bon(?:click|change|submit|keydown)\s*=/i.test(panel),'no inline handlers');
assert.ok(!/https?:\/\//.test(panel),'same-origin panel dependencies');
assert.ok(!/\.html\s*\(/.test(ui+moduleJs),'no unescaped HTML rendering');
const selectors=[...moduleJs.matchAll(/el\('([^']+)'\)/g)].map(m=>'mm-'+m[1]);for(const selector of selectors)assert.ok(ids.includes(selector),'panel selector exists: '+selector);
const jq=function(){};jq.trim=value=>String(value).trim();
const context={window:{jQuery:jq},document:{}};vm.runInNewContext(ui,context);
const api=context.window.EmcoreUI;
for(const [en,fa] of [['2026-10-04','۱۴۰۵/۰۷/۱۲'],['2026-03-21','۱۴۰۵/۰۱/۰۱'],['2025-03-20','۱۴۰۳/۱۲/۳۰'],['2021-03-20','۱۳۹۹/۱۲/۳۰']])assert.equal(api.todayFromGregorian(en),fa);
for(const date of ['۱۴۰۴/۱۲/۳۰','۱۴۰۵/۰۷/۳۱','۱۴۰۵/۰۰/۰۱','۱۴۰۵/۰۱/۰۰'])assert.equal(api.parseDate(date),null,date+' must be invalid');
assert.ok(api.parseDate('۱۴۰۳/۱۲/۳۰'));assert.equal(api.latinDigits('۱۲٣۴'),'1234');
const rollover=api.jalaali.addDays(1404,12,29,1);assert.equal(rollover.jy,1405);assert.equal(rollover.jm,1);assert.equal(rollover.jd,1);
for(const p of ['docs/MEETING_MINUTES_MODULE.md','docs/MEETING_MINUTES_DEPLOYMENT.md','docs/EMCORE_UI_COMPONENTS_MIGRATION.md','database/migrations/013_emcore_meeting_minutes.sql','emcore_api/_minutes_domain.php','emcore_api/_minutes_storage.php','emcore_api/emcore_meeting_minutes.php'])assert.ok(read(p).length>0,p);
assert.ok(!/\bDROP\s+(TABLE|DATABASE)\b/i.test(read('database/migrations/013_emcore_meeting_minutes.sql')),'additive migration');
console.log('Meeting minutes release checks passed: JS syntax, panel wiring, safe rendering, same-origin dependencies and Jalali boundaries.');
